baseURL = "https://tvyal.com/"
languageCode = "en"
title = "Tvyal - Armenian Data Hub"

# Theme
theme = "congo"

# Enable search
enableSearch = true

# Default content language
defaultContentLanguage = "en"

# Enable emoji
enableEmoji = true

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true
