baseURL = "https://tvyal.com/"
title = "Tvyal - Armenian Data Hub"

# Use the newer pagination.pagerSize instead of paginate
[pagination]
  pagerSize = 10

# Theme will be set after we install it properly
# Theme
theme = "congo"

# Basic settings
enableRobotsTXT = true
enableEmoji = true
summaryLength = 0

[languages.en]
  languageName = "English"
  languageCode = "en"
  weight = 1
  [languages.en.params]
    displayName = "EN"
    dateFormat = "January 2, 2006"
    description = "Tvyal - Armenian Data Hub"
  [languages.en.author]
    name = "Tvyal Team"
    headline = "Data Science for Armenia"
    bio = "Armenian Data Hub & Analytics"

[params]
  colorScheme = "congo"
  defaultAppearance = "light"
  autoSwitchAppearance = true
  enableCodeCopy = true
  
[menu]
  [[menu.main]]
    name = "Blog"
    pageRef = "posts"
    weight = 10
  [[menu.main]]
    name = "Data Hub"
    pageRef = "data-hub"
    weight = 20
  [[menu.main]]
    name = "FX Rates"
    pageRef = "fx-rates"
    weight = 30
  [[menu.main]]
    name = "Services"
    pageRef = "services"
    weight = 40
  [[menu.main]]
    name = "About"
    pageRef = "about"
    weight = 50
  [[menu.main]]
    name = "Contact"
    pageRef = "contact"
    weight = 60

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true
